#pragma once
#include <Windows.h>

// This header defines the binary resource for the Intel driver needed by the loader

namespace intel_driver_resource {
    // Define the resource data that will be used for the Intel driver
    // This is normally generated by the bin2header tool but is provided here as a placeholder
    extern const unsigned char driver_resource[];
    extern const size_t driver_resource_len;
}

// Simple stub implementation to allow compilation
namespace intel_driver_resource {
    static const unsigned char driver_resource[] = { 0x00 };
    static const size_t driver_resource_len = sizeof(driver_resource);
}
